export const charactersArray1 = ["../head-soccer-game/images/characters/player-1/Character1.png"
,"../head-soccer-game/images/characters/player-1/Character2.png","../head-soccer-game/images/characters/player-1/Character3.png"
,"../head-soccer-game/images/characters/player-1/Character4.png","../head-soccer-game/images/characters/player-1/Character5.png"
,"../head-soccer-game/images/characters/player-1/Character6.png","../head-soccer-game/images/characters/player-1/Character7.png"
,"../head-soccer-game/images/characters/player-1/Character8.png","../head-soccer-game/images/characters/player-1/Character9.png"
,"../head-soccer-game/images/characters/player-1/Character10.png","../head-soccer-game/images/characters/player-1/Character11.png"
,"../head-soccer-game/images/characters/player-1/Character12.png","../head-soccer-game/images/characters/player-1/Character13.png"
,"../head-soccer-game/images/characters/player-1/Character14.png","../head-soccer-game/images/characters/player-1/Character15.png"
,"../head-soccer-game/images/characters/player-1/Character16.png","../head-soccer-game/images/characters/player-1/Character17.png"
,"../head-soccer-game/images/characters/player-1/Character18.png","../head-soccer-game/images/characters/player-1/Character19.png"
,"../head-soccer-game/images/characters/player-1/Character20.png","../head-soccer-game/images/characters/player-1/Character21.png"
,"../head-soccer-game/images/characters/player-1/Character22.png","../head-soccer-game/images/characters/player-1/Character23.png"
,"../head-soccer-game/images/characters/player-1/Character24.png","../head-soccer-game/images/characters/player-1/Character25.png"
,"../head-soccer-game/images/characters/player-1/Character26.png","../head-soccer-game/images/characters/player-1/Character27.png"
,"../head-soccer-game/images/characters/player-1/Character28.png","../head-soccer-game/images/characters/player-1/Character29.png"];


export const charactersArray2 = ["../head-soccer-game/images/characters/player-2/Character1.png"
,"../head-soccer-game/images/characters/player-2/Character2.png","../head-soccer-game/images/characters/player-2/Character3.png"
,"../head-soccer-game/images/characters/player-2/Character4.png","../head-soccer-game/images/characters/player-2/Character5.png"
,"../head-soccer-game/images/characters/player-2/Character6.png","../head-soccer-game/images/characters/player-2/Character7.png"
,"../head-soccer-game/images/characters/player-2/Character8.png","../head-soccer-game/images/characters/player-2/Character9.png"
,"../head-soccer-game/images/characters/player-2/Character10.png","../head-soccer-game/images/characters/player-2/Character11.png"
,"../head-soccer-game/images/characters/player-2/Character12.png","../head-soccer-game/images/characters/player-2/Character13.png"
,"../head-soccer-game/images/characters/player-2/Character14.png","../head-soccer-game/images/characters/player-2/Character15.png"
,"../head-soccer-game/images/characters/player-2/Character16.png","../head-soccer-game/images/characters/player-2/Character17.png"
,"../head-soccer-game/images/characters/player-2/Character18.png","../head-soccer-game/images/characters/player-2/Character19.png"
,"../head-soccer-game/images/characters/player-2/Character20.png","../head-soccer-game/images/characters/player-2/Character21.png"
,"../head-soccer-game/images/characters/player-2/Character22.png","../head-soccer-game/images/characters/player-2/Character23.png"
,"../head-soccer-game/images/characters/player-2/Character24.png","../head-soccer-game/images/characters/player-2/Character25.png"
,"../head-soccer-game/images/characters/player-2/Character26.png","../head-soccer-game/images/characters/player-2/Character27.png"
,"../head-soccer-game/images/characters/player-2/Character28.png","../head-soccer-game/images/characters/player-2/Character29.png"];