export let charactersArray1 = ["./images/characters/player-1/Character1.png"
,"./images/characters/player-1/Character2.png","./images/characters/player-1/Character3.png"
,"./images/characters/player-1/Character4.png","./images/characters/player-1/Character5.png"
,"./images/characters/player-1/Character6.png","./images/characters/player-1/Character7.png"
,"./images/characters/player-1/Character8.png","./images/characters/player-1/Character9.png"
,"./images/characters/player-1/Character10.png","./images/characters/player-1/Character11.png"
,"./images/characters/player-1/Character12.png","./images/characters/player-1/Character13.png"
,"./images/characters/player-1/Character14.png","./images/characters/player-1/Character15.png"
,"./images/characters/player-1/Character16.png","./images/characters/player-1/Character17.png"
,"./images/characters/player-1/Character18.png","./images/characters/player-1/Character19.png"
,"./images/characters/player-1/Character20.png","./images/characters/player-1/Character21.png"
,"./images/characters/player-1/Character22.png","./images/characters/player-1/Character23.png"
,"./images/characters/player-1/Character24.png","./images/characters/player-1/Character25.png"
,"./images/characters/player-1/Character26.png","./images/characters/player-1/Character27.png"
,"./images/characters/player-1/Character28.png","./images/characters/player-1/Character29.png"];


export let charactersArray2 = ["./images/characters/player-2/Character1.png"
,"./images/characters/player-2/Character2.png","./images/characters/player-2/Character3.png"
,"./images/characters/player-2/Character4.png","./images/characters/player-2/Character5.png"
,"./images/characters/player-2/Character6.png","./images/characters/player-2/Character7.png"
,"./images/characters/player-2/Character8.png","./images/characters/player-2/Character9.png"
,"./images/characters/player-2/Character10.png","./images/characters/player-2/Character11.png"
,"./images/characters/player-2/Character12.png","./images/characters/player-2/Character13.png"
,"./images/characters/player-2/Character14.png","./images/characters/player-2/Character15.png"
,"./images/characters/player-2/Character16.png","./images/characters/player-2/Character17.png"
,"./images/characters/player-2/Character18.png","./images/characters/player-2/Character19.png"
,"./images/characters/player-2/Character20.png","./images/characters/player-2/Character21.png"
,"./images/characters/player-2/Character22.png","./images/characters/player-2/Character23.png"
,"./images/characters/player-2/Character24.png","./images/characters/player-2/Character25.png"
,"./images/characters/player-2/Character26.png","./images/characters/player-2/Character27.png"
,"./images/characters/player-2/Character28.png","./images/characters/player-2/Character29.png"];